### ISSUE TITLE
Drift indexes not found for some BLGCsurvey files.

### ISSUE THREAD

**Issue by luigifcruz** [UCBerkeleySETI/turbo_seti#117]
This issue is happening with some files from the BLGC survey. On startup, `turboSETI` fails to load a missing file called `drift_indexes_array_20.txt`.

[BLGCsurvey_Cband_C07_LARGE](http://blpd9.ssl.berkeley.edu/GC/AGBT19B_999_03/spliced_blc40414243444546o7o0515253545556o7o0616263646566o7o071727374757677_guppi_58702_19960_BLGCsurvey_Cband_C07_0030.gpuspec.0001.fil)
[BLGCsurvey_Cband_C07_MEDIUM](http://blpd12.ssl.berkeley.edu/GC/AGBT19B_999_06/spliced_blc00010203040506o7o0111213141516o7o0212223242526o7o031323334353637_guppi_58704_85754_BLGCsurvey_Cband_C07_0012.gpuspec.8.0001.fil)

```
Traceback (most recent call last):
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/seti_event.py", line 99, in exec
    find_seti_event.search(n_partitions=args.n_parallel,
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/find_doppler.py", line 140, in search
    search_coarse_channel(data_dict, self, filewriter=filewriter, logwriter=logwriter)
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/find_doppler.py", line 202, in search_coarse_channel
    spectra, drift_indices = data_obj.load_data()
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/data_handler.py", line 291, in load_data
    drift_indexes = self.load_drift_indexes()
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/data_handler.py", line 306, in load_drift_indexes
    di_array = np.array(np.genfromtxt(resource_filename('turbo_seti',
  File "/home/luigi/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/luigi/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/luigi/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: /home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/drift_indexes/drift_indexes_array_20.txt not found.
```

**Comment by texadactyl** [comment]
tsteps = 2^20?  Huge!  Maybe never seen before.  (=:
Still downloading the smaller file in question.

**Comment by luigifcruz** [comment]
The Galactic Survey files are pushing the envelope. I just found a 2^23 file.

[BLGCsurvey_Cband_A00 (63 GB)](http://blpd12.ssl.berkeley.edu/GC/AGBT19B_999_20/spliced_blc00010203040506o7o0111213141516o7o0212223242526o7o031323334353637_guppi_58738_00342_BLGCsurvey_Cband_A00_0028.gpuspec.8.0001.fil)

```
drift_indexes_array_23.txt not found.
```

**Comment by texadactyl** [comment]
@telegraphic - Do you have a program for generating additional drift_indexes_array_N.txt files?

**Comment by telegraphic** [comment]
Hi @luigifcruz -- the quick answer is 'don't attempt to use high time resolution files with turboseti'! 

Turboseti is designed to search the for narrowband signals -- the maximum doppler drift we can expect due to the motion of celestial bodies is a few Hz/s. The high time resolution products (ending `0001.fil`) has ~0.5 MHz resolution and ~100 us integrations, so you'd be looking at insane drift rates. 

That said, there are similar algorithms used for pulsar searching on high time resolution files. I believe that the Fast Dispersion Measure Transform (FDMT) is equivalent to the Taylor tree algorithm used in turboseti, but it uses a frequency^-2 shifting schedule instead of linear. 

PS: @texadactyl I'm actually not sure how Emilio generated the drift_indexes files...

**Comment by luigifcruz** [comment]
Hey @telegraphic -- Thanks for the clarification. This makes sense.

Should we throw an exception explaining this particular behaviour to the user before exiting?

**Comment by telegraphic** [comment]
Agreed drift indexes is a red herring so an exception would be useful

**Comment by texadactyl** [comment]
@luigifcruz So, we will go with a ```raise``` that has a better explanation.  Please put this in your code and it will be merged into the base.
