### ISSUE TITLE
Failing to figure out the number of coarse channels.

### ISSUE THREAD

**Issue by luigifcruz** [UCBerkeleySETI/turbo_seti#118]
This issue is happening with some files from the Parkers telescope. Blimpy fails to figure out the number of coarse channels.

[Parkes_58949_50426_GC](http://blpd7.ssl.berkeley.edu/PX600/blc00/guppi_58949_50426_6052121070_GC_A00_0001.0000.h5)
[Parkes_58949_51074_GC](http://blpd7.ssl.berkeley.edu/PX600/blc00/guppi_58949_51074_6052123542_GC_359.94+0.75_0001.0000.h5)

```
Traceback (most recent call last):
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/seti_event.py", line 92, in exec
    find_seti_event = FindDoppler(args.filename, max_drift=args.max_drift,
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/find_doppler.py", line 80, in __init__
    self.data_handle = DATAHandle(datafile, out_dir=out_dir, n_coarse_chan=n_coarse_chan, coarse_chans=coarse_chans, kernels=self.kernels)
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/data_handler.py", line 83, in __init__
    self.data_list = self.__split_h5()
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-2.0.0-py3.8.egg/turbo_seti/find_doppler/data_handler.py", line 149, in __split_h5
    n_coarse_chan = int(fil_file.calc_n_coarse_chan())
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/blimpy-2.0.1-py3.8.egg/blimpy/waterfall.py", line 273, in calc_n_coarse_chan
    n_coarse_chan = self.container.calc_n_coarse_chan(chan_bw)
  File "/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/blimpy-2.0.1-py3.8.egg/blimpy/io/base_reader.py", line 260, in calc_n_coarse_chan
    raise ValueError(errmsg)
ValueError: blimpy:io:base_reader:calc_n_coarse_chan: nchans >= 2**20. Couldn't figure out n_coarse_chan
```

**Comment by texadactyl** [comment]
nchans = ?  I'm downloading the file now but long wait.

If a non-GBT dataset is high resolution (nchans exceeds 2^20), then nchans must be divisible evenly by 2^20.
Otherwise, the dataset is invalid by current assumptions.

Ref: https://github.com/UCBerkeleySETI/blimpy/blob/master/blimpy/io/base_reader.py, starting at line 244

**Comment by texadactyl** [comment]
@luigifcruz This should have been posted against blimpy, not turbo_seti.  We'll fix that after @telegraphic responds.

**Comment by luigifcruz** [comment]
@texadactyl Sure. I was not 100% sure where to post.

**Comment by telegraphic** [comment]
The 'nice' solution here would be to write n_coarse_channels to the filterbank file. There is a flag `-n` on the turboseti command line to manually set number of coarse channels. For Parkes GC data, the coarse channel is actually 128 MHz wide, but I'd suggest using `-n 64` so you search 2 MHz at a time.

**Comment by texadactyl** [comment]
@luigifcruz So, we will go with a raise that has a better explanation. I'll put this in blimpy after recreating this issue where it belongs.

**Comment by texadactyl** [comment]
Closing this and reopened at https://github.com/UCBerkeleySETI/blimpy/issues/156

**Comment by texadactyl** [comment]
@telegraphic 
Neither
FindDoppler(datafile=..., ..., coarse_chans=64)
nor
turboSETI ... -n 64 ...
change the outcome.
