### ISSUE TITLE
README.md specifies no installation instructions nor assumptions

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#14]
Yes, the dependency packages are listed.

I tried Anaconda and it installed.  One of the other Scientists is trying to use pip3 with Python3.  So, I created such an environment and it fails.  What follows is the standard output:
```
python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/test-easy-install-15811.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
```
I tried pointing setuptools to my packages using PYTHONDIR but something insists on the "default".

Please update README.md to include installation recipe along with any assumptions.  Thank you.

**Comment by texadactyl** [comment]
By the way, the setup.py BUILD step had no trouble finding the right lib tree:
```
python3 setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/turbo_seti
copying turbo_seti/__init__.py -> build/lib.linux-x86_64-3.6/turbo_seti
creating build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/file_writers.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/seti_event.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/__init__.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/plot_candidates.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/data_handler.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/helper_functions.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/findopp.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/find_candidates.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
copying turbo_seti/findoppler/fits_wrapper.py -> build/lib.linux-x86_64-3.6/turbo_seti/findoppler
creating build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_2.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_3.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_4.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_5.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_6.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_7.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_8.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_9.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_10.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
copying turbo_seti/drift_indexes/drift_indexes_array_11.txt -> build/lib.linux-x86_64-3.6/turbo_seti/drift_indexes
running build_ext
building 'turbo_seti.findoppler.taylor_tree' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/turbo_seti
creating build/temp.linux-x86_64-3.6/turbo_seti/findoppler
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/elkins/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c turbo_seti/findoppler/taylor_tree.c -o build/temp.linux-x86_64-3.6/turbo_seti/findoppler/taylor_tree.o
In file included from /home/elkins/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /home/elkins/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/elkins/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from turbo_seti/findoppler/taylor_tree.c:632:
/home/elkins/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/turbo_seti/findoppler/taylor_tree.o -o build/lib.linux-x86_64-3.6/turbo_seti/findoppler/taylor_tree.cpython-36m-x86_64-linux-gnu.so
```

**Comment by texadactyl** [comment]
I found a fix to setup.py which allows the installation to proceed in a pip3 environment; probably works for Python 2 / pip as well.  

Attached is a proposed update to setup.py.

[setup.py.txt](https://github.com/UCBerkeleySETI/turbo_seti/files/2775853/setup.py.txt)

**Comment by texadactyl** [comment]
My experience with a tiny program including trubo_seti as a package is documented here:
[https://github.com/UCBerkeleySETI/turbo_seti/issues/11#issuecomment-455809881](url)

**Comment by texadactyl** [comment]
I can now install with Python3 (Anaconda environment) as follows:
`python3 setup.py install`

Is that the correct methodology?

How about execution?  The READ.md instructions say do this:
`turboSETI Voyager1.single_coarse.fine_res.h5`

But, this never works because of some plugin issue and there are no instructions that I can find.
Sample output:
`turboSETI Voyager1.single_coarse.fine_res.h5
blimpy.file_wrapper INFO     Skipping loading data ...
root            ERROR    Error accessing header from file: Voyager1.single_coarse.fine_res.h5.
Traceback (most recent call last):
  File "/home/elkins/anaconda3/lib/python3.6/site-packages/turbo_seti-0.8.1-py3.6-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 147, in __init__
    header = self.__make_data_header(self.fil_file.header)
  File "/home/elkins/anaconda3/lib/python3.6/site-packages/turbo_seti-0.8.1-py3.6-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 219, in __make_data_header
    base_header[u'SOURCE'] = header[u'source_name'].replace('\xc2\xa0','_').replace(' ','_')
KeyError: 'source_name'
`

**Comment by telegraphic** [comment]
I am rolling this one into #22, so closing.

**Comment by texadactyl** [comment]
This may be a nit but those are two different things - tutorial versus README.md installation instructions.

Installation:
1. Download and unzip
2. cd into master.
3. Execute: python3 setup.py install  #  ignore warnings

If it were me, I'd insert installation instructions just before the "Usage" section.

In the "Use as a package" section, you can remove the "> " prefixes and the first import statement.  Or, just show this as a working example:
```
"""
Turbo Seti FinDoppler Test
"""
from turbo_seti.findoppler.findopp import FinDoppler

DATA = $HOME/data/Voyager1.single_coarse.fine_res.h5"
fd = FinDoppler(DATA, 2, out_dir="$HOME/data/")
fd.search()

```
