### ISSUE TITLE
"Failed in nopython mode" error when attempting to run turboSETI

### ISSUE THREAD

**Issue by ewhite42** [UCBerkeleySETI/turbo_seti#144]
I am encountering an error when attempting to run turboSETI, and I hope it's ok to ask a question about that here. I installed turboSETI on my home computer yesterday in an Anaconda3 environment following the steps outlined here: [https://github.com/UCBerkeleySETI/turbo_seti/blob/master/tutorial/turboSETI_tutorial.ipynb](https://github.com/UCBerkeleySETI/turbo_seti/blob/master/tutorial/turboSETI_tutorial.ipynb), and attempted to run the program on some files from a GBT observation of Voyager last summer using this script: 

```
import os
import pylab as plt
from blimpy import Waterfall
import turbo_seti.find_doppler.seti_event as turbo
import turbo_seti.find_event as find
from turbo_seti.find_doppler.find_doppler import FindDoppler

print("Imports successful!")

infile_name = 'VoyagerData/new_dat_files.lst'
infile = open(infile_name, 'r')

voyager_list = ['/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5']

print(voyager_list)

i = 0

for file in voyager_list:
    doppler = FindDoppler(file,
                      max_drift = 4,
                      snr = 10,       
                      out_dir = './' # This is where the turboSETI output files will be stored. "./" is the current directory
                      )
    doppler.search()
    i += 1
    print("finished searching file {0}".format(i))
```

However, when I run this program in python3, I get the following output: 

```
Imports successful!
['/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5', '/home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5']
find_doppler    INFO     {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.38671875, 'foff': -2.7939677238464355e-06, 'machine_id': 20, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'source_name': 'VOYAGER-1', 'src_dej': <Angle 12.40378167 deg>, 'src_raj': <Angle 17.21124472 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59046.92634259259, 'za_start': 0.0}
find_doppler    INFO     Recreating DAT and LOG files
find_doppler    INFO     Start ET search for /home/ellie/research/seti/VoyagerTutorial2/VoyagerData/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5
Traceback (most recent call last):
  File "/home/ellie/research/seti/VoyagerTutorial2/run_turboSETI.py", line 29, in <module>
    doppler.search()
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/turbo_seti/find_doppler/find_doppler.py", line 161, in search
    search_coarse_channel(dl, self, dataloader=sched, filewriter=filewriter, logwriter=logwriter)
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/turbo_seti/find_doppler/find_doppler.py", line 225, in search_coarse_channel
    data_obj, spectra, drift_indices = dataloader.get()
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/turbo_seti/find_doppler/kernels/Scheduler/__init__.py", line 36, in get
    result = f.result()
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/turbo_seti/find_doppler/find_doppler.py", line 176, in load_data
    spectra, drift_indices = data_obj.load_data()
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/turbo_seti/find_doppler/data_handler.py", line 266, in load_data
    self.fil_file.blank_dc(n_coarse_chan)
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/blimpy/waterfall.py", line 356, in blank_dc
    parse(self.data, n_coarse_chan, n_chan_per_coarse, mid_chan)
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function median at 0x7fa47776fca0>) found for signature:
 
 >>> median(array(float32, 3d, A))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'np_median': File: numba/np/arraymath.py: Line 1254.
    With argument(s): '(array(float32, 3d, A))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<function _median_inner at 0x7fa44a261550>) found for signature:
    
    >>> _median_inner(array(float32, 1d, C), int64)
    
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 150.
           With argument(s): '(array(float32, 1d, C), int64)':
          Rejected as the implementation raised a specific error:
            TypingError: Failed in nopython mode pipeline (step: nopython frontend)
          No implementation of function Function(<function _select_two at 0x7fa44a261430>) found for signature:
           
           >>> _select_two(array(float32, 1d, C), int64, Literal[int](0), int64)
           
          There are 2 candidate implementations:
                - Of which 2 did not match due to:
                Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 150.
                  With argument(s): '(array(float32, 1d, C), int64, int64, int64)':
                 Rejected as the implementation raised a specific error:
                   UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
                 Use of unsupported opcode (LOAD_ASSERTION_ERROR) found
                 
                 File "../../../src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/np/arraymath.py", line 1222:
                 def _select_two(arry, k, low, high):
                     <source elided>
                     while True:
                         assert high > low  # by construction
                         ^
          
            raised from /home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/core/byteflow.py:269
          
          During: resolving callee type: Function(<function _select_two at 0x7fa44a261430>)
          During: typing of call at /home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/np/arraymath.py (1248)
          
          
          File "../../../src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/np/arraymath.py", line 1248:
          def _median_inner(temp_arry, n):
              <source elided>
              if n & 1 == 0:
                  a, b = _select_two(temp_arry, half - 1, low, high)
                  ^
   
     raised from /home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/core/typeinfer.py:1071
   
   During: resolving callee type: Function(<function _median_inner at 0x7fa44a261550>)
   During: typing of call at /home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/np/arraymath.py (1264)
   
   
   File "../../../src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/np/arraymath.py", line 1264:
       def median_impl(a):
           <source elided>
           n = temp_arry.shape[0]
           return _median_inner(temp_arry, n)
           ^

  raised from /home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/numba/core/typeinfer.py:1071

During: resolving callee type: Function(<function median at 0x7fa47776fca0>)
During: typing of call at /home/ellie/src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/blimpy/waterfall.py (354)


File "../../../src/anaconda3/envs/turboSETI/lib/python3.9/site-packages/blimpy/waterfall.py", line 354:
        def parse(data, n_coarse_chan, n_chan_per_coarse, mid_chan):
            <source elided>
                ss = ii*n_chan_per_coarse
                data[..., ss+mid_chan] = np.median(data[..., ss+mid_chan+5:ss+mid_chan+10])
                ^
```

Is this some kind of user error or an issue with turboSETI itself? Thank you so much for taking a look at this, and for your time.

**Comment by texadactyl** [comment]
I think that you have some sort of environment problem or set of problems.  I cannot reproduce your symptoms.

**Comment by texadactyl** [comment]
I think that you have some sort of environment problem or set of problems. I cannot reproduce your symptoms.

I modified your program so that I could run it on my own laptop.  Thankfully, I already had the same HDF5 files.
```
from turbo_seti.find_doppler.find_doppler import FindDoppler

print("Imports successful!")

H5DIR = '/seti_data/voyager_2020/'

voyager_list = [H5DIR + 'single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5', 
                H5DIR + 'single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5', 
                H5DIR + 'single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5', 
                H5DIR + 'single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5', 
                H5DIR + 'single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5', 
                H5DIR + 'single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5']

print(voyager_list)

i = 0

for file in voyager_list:
    doppler = FindDoppler(file,
                      max_drift = 4,
                      snr = 10,       
                      out_dir = H5DIR
                      )
    doppler.search()
    i += 1
    print("finished searching file {0}".format(i))
```

Here is the standard output:
```
Imports successful!
['/seti_data/voyager_2020/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5', '/seti_data/voyager_2020/single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5', '/seti_data/voyager_2020/single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5', '/seti_data/voyager_2020/single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5', '/seti_data/voyager_2020/single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5', '/seti_data/voyager_2020/single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5']
find_doppler    INFO     {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.38671875, 'foff': -2.7939677238464355e-06, 'machine_id': 20, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'source_name': 'VOYAGER-1', 'src_dej': <Angle 12.40378167 deg>, 'src_raj': <Angle 17.21124472 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59046.92634259259, 'za_start': 0.0}
find_doppler    INFO     Recreating DAT and LOG files
find_doppler    INFO     Start ET search for /seti_data/voyager_2020/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5
find_doppler.0  INFO     ===== coarse_channel=0, f_start=8418.45703125, f_stop=8421.38671875
find_doppler.0  INFO     Top hit found! SNR: 22.328960 ... index: 651879
find_doppler.0  INFO     Top hit found! SNR: 192.893808 ... index: 659989
find_doppler.0  INFO     Top hit found! SNR: 22.572284 ... index: 667983
find_doppler.0  INFO     Total number of candidates for coarse channel 0 is: 22944
finished searching file 1
find_doppler.0  INFO     {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.38671875, 'foff': -2.7939677238464355e-06, 'machine_id': 20, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'source_name': 'VOYAGER-1', 'src_dej': <Angle 12.40379333 deg>, 'src_raj': <Angle 17.211245 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59046.933703703704, 'za_start': 0.0}
find_doppler.0  INFO     Recreating DAT and LOG files
find_doppler.0  INFO     Start ET search for /seti_data/voyager_2020/single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5
find_doppler.0  INFO     ===== coarse_channel=0, f_start=8418.45703125, f_stop=8421.38671875
find_doppler.0  INFO     Top hit found! SNR: 10.996473 ... index: 651964
find_doppler.0  INFO     Top hit found! SNR: 82.802052 ... index: 660074
find_doppler.0  INFO     Top hit found! SNR: 10.476845 ... index: 668184
find_doppler.0  INFO     Total number of candidates for coarse channel 0 is: 624
finished searching file 2
find_doppler.0  INFO     {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.38671875, 'foff': -2.7939677238464355e-06, 'machine_id': 20, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'source_name': 'VOYAGER-1', 'src_dej': <Angle 11.40377306 deg>, 'src_raj': <Angle 17.21124389 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59046.944768518515, 'za_start': 0.0}
find_doppler.0  INFO     Recreating DAT and LOG files
find_doppler.0  INFO     Start ET search for /seti_data/voyager_2020/single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5
find_doppler.0  INFO     ===== coarse_channel=0, f_start=8418.45703125, f_stop=8421.38671875
find_doppler.0  INFO     Total number of candidates for coarse channel 0 is: 0
finished searching file 3
find_doppler.0  INFO     {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.38671875, 'foff': -2.7939677238464355e-06, 'machine_id': 20, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'source_name': 'VOYAGER-1', 'src_dej': <Angle 12.40378 deg>, 'src_raj': <Angle 17.21124361 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59046.941087962965, 'za_start': 0.0}
find_doppler.0  INFO     Recreating DAT and LOG files
find_doppler.0  INFO     Start ET search for /seti_data/voyager_2020/single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5
find_doppler.0  INFO     ===== coarse_channel=0, f_start=8418.45703125, f_stop=8421.38671875
find_doppler.0  INFO     Top hit found! SNR: 18.529706 ... index: 652058
find_doppler.0  INFO     Top hit found! SNR: 145.125469 ... index: 660166
find_doppler.0  INFO     Top hit found! SNR: 19.028457 ... index: 668162
find_doppler.0  INFO     Total number of candidates for coarse channel 0 is: 4390
finished searching file 4
find_doppler.0  INFO     {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.38671875, 'foff': -2.7939677238464355e-06, 'machine_id': 20, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'source_name': 'VOYAGER-1', 'src_dej': <Angle 12.40376944 deg>, 'src_raj': <Angle 17.27950361 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59046.937372685185, 'za_start': 0.0}
find_doppler.0  INFO     Recreating DAT and LOG files
find_doppler.0  INFO     Start ET search for /seti_data/voyager_2020/single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5
find_doppler.0  INFO     ===== coarse_channel=0, f_start=8418.45703125, f_stop=8421.38671875
find_doppler.0  INFO     Total number of candidates for coarse channel 0 is: 0
finished searching file 5
find_doppler.0  INFO     {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8421.38671875, 'foff': -2.7939677238464355e-06, 'machine_id': 20, 'nbits': 32, 'nchans': 1048576, 'nifs': 1, 'source_name': 'VOYAGER-1', 'src_dej': <Angle 13.40378444 deg>, 'src_raj': <Angle 17.211245 hourangle>, 'telescope_id': 6, 'tsamp': 18.253611007999982, 'tstart': 59046.93002314815, 'za_start': 0.0}
find_doppler.0  INFO     Recreating DAT and LOG files
find_doppler.0  INFO     Start ET search for /seti_data/voyager_2020/single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5
find_doppler.0  INFO     ===== coarse_channel=0, f_start=8418.45703125, f_stop=8421.38671875
find_doppler.0  INFO     Total number of candidates for coarse channel 0 is: 0
finished searching file 6
```

The following is how I set up for testing in an Anaconda environment:
```
Downloaded Anaconda from https://www.anaconda.com/products/individual
In a terminal window, cd Downloads; bash A*.sh
Logout; login.
Open a terminal window.
conda update conda
conda create -name tutorial_env or whatever environment name that you would like
conda activate tutorial_env
python3 -m pip install -U git+https://github.com/UCBerkeleySETI/blimpy
python3 -m pip install -U git+https://github.com/UCBerkeleySETI/turbo_seti
```

**Comment by texadactyl** [comment]
Notice that I created a conda environment "seti" that is separate from the conda base.  If something bad happens in "seti", I can purge it without worrying about the conda base.

**Comment by ewhite42** [comment]
Ah, thanks so much for getting back to me on this -- you were right, it seems to have been a pip-related issue. When I installed using `python3 -m pip install [etc]`, I was able to get everything working. I had done `conda install pip`, then just used `pip install [etc]`, so that must have been the problem. Really appreciate you pointing me in the right direction on this!
