### ISSUE TITLE
find_event_pipeline -- UnicodeDecodeError

### ISSUE THREAD

**Issue by ewhite42** [UCBerkeleySETI/turbo_seti#145]
I have been running into some errors when trying to run find_event_pipeline using the following script: 

```
from turbo_seti.find_event.find_event_pipeline import find_event_pipeline

dat_file = open('VoyagerData/new_dat_files.lst', 'r')
lines = dat_file.readlines()
dat_files = []

for line in lines:
    dat_files.append(line.strip())

num_in_cadence = len(dat_files)
find_event_pipeline('VoyagerData/new_dat_files.lst', filter_threshold = 3, number_in_cadence = num_in_cadence)
```
When I run this with python3, I get this output: 

```
************   BEGINNING FIND_EVENT PIPELINE   **************
Assuming the first observation is an ON
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
There are 6 total files in the filelist VoyagerData/new_dat_files.lst
therefore, looking for events in 1 on-off set(s)
with a minimum SNR of 10
Present in all A sources with RFI rejection from the off-sources
not including signals with zero drift
saving the output files
***       DIAG       ***
------   o   -------
Loading data...
Traceback (most recent call last):
  File "run_find_event.py", line 11, in <module>
    find_event_pipeline('VoyagerData/new_dat_files.lst', filter_threshold = 3, number_in_cadence = num_in_cadence)
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/turbo_seti/find_event/find_event_pipeline.py", line 205, in find_event_pipeline
    cand = find_event.find_events(file_sublist, 
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/turbo_seti/find_event/find_event.py", line 334, in find_events
    on_table_i = make_table(dat_file)
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/turbo_seti/find_event/find_event.py", line 146, in make_table
    df_data = read_dat(filename)
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/turbo_seti/find_event/find_event.py", line 56, in read_dat
    hits = file_dat.readlines()
  File "/home/ellie/src/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Thanks so much for taking a look at this; I would be grateful for any advice on how to troubleshoot this problem!

**Comment by texadactyl** [comment]
I suggested corrected program which makes the DAT files and then runs find_event_pipeline().

```
from shutil import rmtree
from os import mkdir
import logging
from turbo_seti.find_doppler.find_doppler import FindDoppler
from turbo_seti.find_event.find_event_pipeline import find_event_pipeline

H5DIR = '/seti_data/voyager_2020/'
OUTDIR = H5DIR + 'outdir/'
PATH_DAT_LIST_FILE = OUTDIR + 'new_dat_files.lst'
PATH_CSVF = OUTDIR + 'found_event_table.csv'

voyager_list = ['single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5',
                'single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5',
                'single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5',
                'single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5',
                'single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5',
                'single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5']

def make_dat_files():
    ii = 0
    with open(PATH_DAT_LIST_FILE, 'w') as file_handle:
        for filename in voyager_list:
            path_h5 = H5DIR + filename
            doppler = FindDoppler(path_h5,
                              max_drift = 4,
                              snr = 10,
                              log_level_int=logging.WARNING,
                              out_dir = H5DIR
                              )
            doppler.search()
            ii += 1
            path_dat = H5DIR + filename.replace('.h5', '.dat')
            file_handle.write('{}\n'.format(path_dat))
            print("make_dat_files: {} - finished making DAT file for {}".format(ii, path_h5))

# Initialize output directory
rmtree(OUTDIR, ignore_errors=True)
mkdir(OUTDIR)

# Make the DAT files
make_dat_files()

# Generate CSV file from find_event_pipeline()
num_in_cadence = len(voyager_list)
find_event_pipeline(PATH_DAT_LIST_FILE,
                    filter_threshold = 3,
                    number_in_cadence = num_in_cadence,
                    user_validation=False,
                    saving=True,
                    csv_name=PATH_CSVF)
print("Produced {}".format(PATH_CSVF))
```

Try filter_threshold values 1 and 2 as well.

**Comment by texadactyl** [comment]
From the find_event_pipeline() source code:
```
    filter_threshold : int
        Specification for how strict the hit filtering will be.
        There are 3 different levels of filtering, specified by
        the integers 1, 2, and 3. Filter_threshold = 1 
        returns hits above an SNR cut, taking into account the
        check_zero_drift parameter, but without an ON-OFF check.
        Filter_threshold = 2 returns hits that passed level 1
        AND that are in at least one ON but no OFFs. 
        Filter_threshold = 3 returns events that passed level 2
        AND that are present in *ALL* ONs.

```

**Comment by texadactyl** [comment]
Threshold level 1 should get you something although there are more exciting H5 files than those of Voyager.

**Comment by texadactyl** [comment]
Next: plot_event_pipeline?

**Comment by ewhite42** [comment]
Thanks so much for the tips, I was able to get a bit further this time. If I run the program as you have it above, it goes all the way through and yields no candidates. I realized that I had the file names in the wrong order (some of the ONs got labelled as OFFs), though, and when I reordered them as follows: 

```
voyager_list = ['single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5',
                'single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5',
                'single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5',
                'single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5',
                'single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5',
                'single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5']
```

and re-run the program, it yields the following output: 

```
make_dat_files: 1 - finished making DAT file for VoyagerData/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.h5
make_dat_files: 2 - finished making DAT file for VoyagerData/single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.h5
make_dat_files: 3 - finished making DAT file for VoyagerData/single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.h5
make_dat_files: 4 - finished making DAT file for VoyagerData/single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.h5
make_dat_files: 5 - finished making DAT file for VoyagerData/single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.h5
make_dat_files: 6 - finished making DAT file for VoyagerData/single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.h5

************   BEGINNING FIND_EVENT PIPELINE   **************

Assuming the first observation is an ON
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
find_event_pipeline: source_name = VOYAGER-1
There are 6 total files in the filelist VoyagerData/outdir/new_dat_files.lst
therefore, looking for events in 1 on-off set(s)
with a minimum SNR of 10
Present in all A sources with RFI rejection from the off-sources
not including signals with zero drift
saving the output files

***       DIAG       ***

------   o   -------
Loading data...
Loaded 3 hits from VoyagerData/single_coarse_guppi_59046_80036_DIAG_VOYAGER-1_0011.rawspec.0000.dat (ON)
Loaded 0 hits from VoyagerData/single_coarse_guppi_59046_80354_DIAG_VOYAGER-1_0012.rawspec.0000.dat (OFF)
Loaded 3 hits from VoyagerData/single_coarse_guppi_59046_80672_DIAG_VOYAGER-1_0013.rawspec.0000.dat (ON)
Loaded 0 hits from VoyagerData/single_coarse_guppi_59046_80989_DIAG_VOYAGER-1_0014.rawspec.0000.dat (OFF)
Loaded 3 hits from VoyagerData/single_coarse_guppi_59046_81310_DIAG_VOYAGER-1_0015.rawspec.0000.dat (ON)
Loaded 0 hits from VoyagerData/single_coarse_guppi_59046_81628_DIAG_VOYAGER-1_0016.rawspec.0000.dat (OFF)
All data loaded!

Finding events in this cadence...
numexpr.utils   INFO     Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Found a total of 9 hits above the SNR cut in this cadence!
Traceback (most recent call last):
  File "run_turboSETI.py", line 47, in <module>
    find_event_pipeline(PATH_DAT_LIST_FILE,
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/turbo_seti/find_event/find_event_pipeline.py", line 205, in find_event_pipeline
    cand = find_event.find_events(file_sublist, 
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/turbo_seti/find_event/find_event.py", line 417, in find_events
    snr_adjusted_table['RFI_in_range'] = snr_adjusted_table.apply(lambda hit: len(off_table[((off_table['Freq'] > calc_freq_range(hit)[0]) & (off_table['Freq'] < calc_freq_range(hit)[1]))]),axis=1)
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 7548, in apply
    return op.get_result()
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_standard()
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 271, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 300, in apply_series_generator
    results[i] = self.f(v)
  File "/home/ellie/src/anaconda3/lib/python3.8/site-packages/turbo_seti/find_event/find_event.py", line 417, in <lambda>
    snr_adjusted_table['RFI_in_range'] = snr_adjusted_table.apply(lambda hit: len(off_table[((off_table['Freq'] > calc_freq_range(hit)[0]) & (off_table['Freq'] < calc_freq_range(hit)[1]))]),axis=1)
TypeError: list indices must be integers or slices, not str
```

Any thoughts on what could be causing this? Thanks again!

**Comment by texadactyl** [comment]
I just reproduced those symptoms.  Scratching my head at the moment.

**Comment by texadactyl** [comment]
Editorial - this is one of the WORST Python statements that I have ever seen:
```
    snr_adjusted_table['RFI_in_range'] = snr_adjusted_table.apply(lambda hit: len(off_table[((off_table['Freq'] > calc_freq_range(hit)[0]) & (off_table['Freq'] < calc_freq_range(hit)[1]))]),axis=1)

```
