### ISSUE TITLE
README.md installation requirements: package bitshuffle, environment variable HDF5_PLUGIN_PATH 

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#16]
Starting with a stable Xubuntu 18.04.1 and Python 2.7.15rc1.
Created a new user and logged in as that user.
```sudo chmod -R a+rw /usr/local # don't want a chance of a permissions error```
```pip install astropy cython h5py imageio lightkurve matplotlib numpy pytest scipy```
Downloaded turbo_seti and unzipped it to $HOME/Downloads.
```cd $HOME/Downloads/turbo_seti-master/```
```python setup.py install```
Everything compiled and installed well.
Try sample voyager h5:
```
cd voyager_test
turboSETI Voyager1.single_coarse.fine_res.h5
blimpy.file_wrapper INFO     Skipping loading data ...
blimpy.file_wrapper INFO     Skipping loading data ...
turbo_seti.findoppler.findopp INFO     {u'telescope_id': 6, u'nbits': 32, u'fch1': 8421.386717353016, u'tstart': 57650.78209490741, u'data_type': 1, u'nchans': 1048576, u'ibeam': 1, u'tsamp': 18.253611008, u'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', u'foff': -2.7939677238464355e-06, u'DIMENSION_LABELS': array(['frequency', 'feed_id', 'time'], dtype=object), u'src_raj': <Angle 17.16777333 hourangle>, u'src_dej': <Angle 12.183 deg>, u'nbeams': 1, u'az_start': 0.0, u'source_name': 'Voyager1', u'nifs': 1, u'machine_id': 20, u'za_start': 0.0}
turbo_seti.findoppler.findopp INFO     A new FinDoppler instance created!
turbo_seti.findoppler.findopp INFO     Start ET search for Voyager1.single_coarse.fine_res.h5
turbo_seti.findoppler.findopp INFO     Start searching for coarse channel: 1
root            ERROR    Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/seti_event.py", line 76, in main
    find_seti_event.search()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/findopp.py", line 88, in search
    self.search_data(target_data_obj)
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/findopp.py", line 102, in search_data
    spectra, drift_indexes = data_obj.load_data()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/data_handler.py", line 174, in load_data
    self.fil_file.read_data(f_start=self.f_start, f_stop=self.f_stop)
  File "/usr/local/lib/python2.7/dist-packages/blimpy-1.3.5-py2.7.egg/blimpy/waterfall.py", line 156, in read_data
    self.container.read_data(f_start=f_start, f_stop=f_stop,t_start=t_start, t_stop=t_stop)
  File "/usr/local/lib/python2.7/dist-packages/blimpy-1.3.5-py2.7.egg/blimpy/file_wrapper.py", line 435, in read_data
    self.data = self.h5["data"][self.t_start:self.t_stop,:,self.chan_start_idx:self.chan_stop_idx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/python2/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
IOError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
Traceback (most recent call last):
  File "/usr/local/bin/turboSETI", line 11, in <module>
    load_entry_point('turbo-seti==0.7.3', 'console_scripts', 'turboSETI')()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/seti_event.py", line 84, in main
Exception: (1, '[turbo_SETI] Some issue with FinDoppler.', IOError("Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)",))
```
It's true that there is no tree on my system rooted at /usr/local/hdf5/.  What process creates whatever is "missing"?  I have h5py installed.  Is that supposed to be sufficient?

**Comment by texadactyl** [comment]
So, I guessed that required filter bitshuffle is not installed.  This worked:
```pip install bitshuffle```

Try again:
```
turboSETI Voyager1.single_coarse.fine_res.h5
blimpy.file_wrapper INFO     Skipping loading data ...
blimpy.file_wrapper INFO     Skipping loading data ...
turbo_seti.findoppler.findopp INFO     {u'telescope_id': 6, u'nbits': 32, u'fch1': 8421.386717353016, u'tstart': 57650.78209490741, u'data_type': 1, u'nchans': 1048576, u'ibeam': 1, u'tsamp': 18.253611008, u'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', u'foff': -2.7939677238464355e-06, u'DIMENSION_LABELS': array(['frequency', 'feed_id', 'time'], dtype=object), u'src_raj': <Angle 17.16777333 hourangle>, u'src_dej': <Angle 12.183 deg>, u'nbeams': 1, u'az_start': 0.0, u'source_name': 'Voyager1', u'nifs': 1, u'machine_id': 20, u'za_start': 0.0}
turbo_seti.findoppler.findopp INFO     A new FinDoppler instance created!
turbo_seti.findoppler.findopp INFO     Start ET search for Voyager1.single_coarse.fine_res.h5
turbo_seti.findoppler.findopp INFO     Start searching for coarse channel: 1
root            ERROR    Can't read data (required filter 'bitshuffle; see https://github.com/kiyo-masui/bitshuffle' is not registered)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/seti_event.py", line 76, in main
    find_seti_event.search()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/findopp.py", line 88, in search
    self.search_data(target_data_obj)
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/findopp.py", line 102, in search_data
    spectra, drift_indexes = data_obj.load_data()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/data_handler.py", line 174, in load_data
    self.fil_file.read_data(f_start=self.f_start, f_stop=self.f_stop)
  File "/usr/local/lib/python2.7/dist-packages/blimpy-1.3.5-py2.7.egg/blimpy/waterfall.py", line 156, in read_data
    self.container.read_data(f_start=f_start, f_stop=f_stop,t_start=t_start, t_stop=t_stop)
  File "/usr/local/lib/python2.7/dist-packages/blimpy-1.3.5-py2.7.egg/blimpy/file_wrapper.py", line 435, in read_data
    self.data = self.h5["data"][self.t_start:self.t_stop,:,self.chan_start_idx:self.chan_stop_idx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/python2/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
IOError: Can't read data (required filter 'bitshuffle; see https://github.com/kiyo-masui/bitshuffle' is not registered)
Traceback (most recent call last):
  File "/usr/local/bin/turboSETI", line 11, in <module>
    load_entry_point('turbo-seti==0.7.3', 'console_scripts', 'turboSETI')()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/seti_event.py", line 84, in main
Exception: (1, '[turbo_SETI] Some issue with FinDoppler.', IOError("Can't read data (required filter 'bitshuffle; see https://github.com/kiyo-masui/bitshuffle' is not registered)",))
```

Note the last message:
```see https://github.com/kiyo-masui/bitshuffle' is not registered```

Registered?

**Comment by texadactyl** [comment]
It would be helpful if the README.md could be updated with an installation paragraph with a step-by-step recipe for installing and executing against the sample voyager h5.

**Comment by texadactyl** [comment]
Being the relentless sort that I am, I guessed after googling that I needed to setup some sort of plugin path.  It turned out to be a good guess:

```
export HDF5_PLUGIN_PATH=$HOME/.local/lib/python2.7/site-packages/bitshuffle/plugin/
turboSETI Voyager1.single_coarse.fine_res.h5
blimpy.file_wrapper INFO     Skipping loading data ...
blimpy.file_wrapper INFO     Skipping loading data ...
turbo_seti.findoppler.findopp INFO     {u'telescope_id': 6, u'nbits': 32, u'fch1': 8421.386717353016, u'tstart': 57650.78209490741, u'data_type': 1, u'nchans': 1048576, u'ibeam': 1, u'tsamp': 18.253611008, u'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', u'foff': -2.7939677238464355e-06, u'DIMENSION_LABELS': array(['frequency', 'feed_id', 'time'], dtype=object), u'src_raj': <Angle 17.16777333 hourangle>, u'src_dej': <Angle 12.183 deg>, u'nbeams': 1, u'az_start': 0.0, u'source_name': 'Voyager1', u'nifs': 1, u'machine_id': 20, u'za_start': 0.0}
turbo_seti.findoppler.findopp INFO     A new FinDoppler instance created!
turbo_seti.findoppler.findopp INFO     Start ET search for Voyager1.single_coarse.fine_res.h5
turbo_seti.findoppler.findopp INFO     Start searching for coarse channel: 1
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Top hit found! SNR: 30.612128 ... index: 739933
turbo_seti.findoppler.findopp INFO     Top hit found! SNR: 245.707984 ... index: 747929
turbo_seti.findoppler.findopp INFO     Top hit found! SNR: 31.220652 ... index: 756037
turbo_seti.findoppler.findopp INFO     Total number of candidates for coarse channel 1 is: 858
Search time:  1.05 min
```

**Comment by texadactyl** [comment]
Logging suggestions for whatever its worth:
- In seti_event, put the elapsed searched time in the log.
```
logger = logging.getLogger(__name__)
logger.info(...)
```
- In the other modules using ```print``` (find_candidates, fits_wrapper, and plot_candidates), switch to using logger.{info,debug,error} as appropriate for the context.

**Comment by texadactyl** [comment]
I found another example of using the HDF5_PLUGIN_PATH environment variable, this time with the h5dump utility which employs an lzf filter (plugin):
[https://github.com/h5py/h5py/pull/506](url)

**Comment by texadactyl** [comment]
A more elegant fix to this issue: Modify seti_event.py to have as the top-most import statement:
```import hdf5plugin```

Then, there is no need to explicitly set the environment variable outside the program nor know where exactly the plugin resides.

**Comment by jeenriquez** [comment]
Hey @texadactyl, thanks for all the hard work the last couple of weeks! I have been occupied elsewhere, but will be looking into this more starting next week. 
Following on your comments above. I'm wondering which version of h5py you are using. We were having an issue using bitshuffle with any version h5py > 2.5.0 , we currently have this work around mentioned in the blimpy installation: ```pip install --no-binary=h5py h5py```. I'm wondering what happens if you install it this way.

**Comment by texadactyl** [comment]
h5py 2.9.0 (latest version)

**Comment by texadactyl** [comment]
I agree with solving the HDF5_PLUGIN_PATH issue in blimpy.
Therefore, closing this.
