### ISSUE TITLE
trouble compiling turboSETI

### ISSUE THREAD

**Issue by dmkunsman** [UCBerkeleySETI/turbo_seti#18]
Hello, about a month ago I was able to compile turboSETI, but after upgrading my computer and blimpy.  I have not been able to compile turboSETI again.  These are my errors when I type turboSETI in the command prompt

C:\Users\Bourbaki\Desktop\turbo_seti\turbo_seti>turboSETI
Warning: Cannot import main utilities
Warning: Cannot import HDF5 utilities
c:\Python27\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of
the second argument of issubdtype from `float` to `np.floating` is deprecated. I
n future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "c:\Python27\Scripts\turboSETI-script.py", line 11, in <module>
    load_entry_point('turbo-seti==0.7.3', 'console_scripts', 'turboSETI')()
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 570, in l
oad_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2751, in
load_entry_point
    return ep.load()
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2405, in
load
    return self.resolve()
  File "c:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2411, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build\bdist.win-amd64\egg\turbo_seti\__init__.py", line 1, in <module>
  File "build\bdist.win-amd64\egg\turbo_seti\findoppler\seti_event.py", line 3,
in <module>
  File "build\bdist.win-amd64\egg\turbo_seti\findoppler\findopp.py", line 17, in
 <module>
  File "build\bdist.win-amd64\egg\turbo_seti\findoppler\data_handler.py", line 7
, in <module>
ImportError: cannot import name Waterfall

**Comment by jeenriquez** [comment]
I'm not be able to recreate your issue, likely since I don't have a windows machine. But, it seems to me that you may want to make sure that you are able to import Waterall (blimpy).  If you can't then please transfer this issue to the blimpy github.  I'm using the latest version of both blimpy and turboSETI and it is working for me. 
You could try installing through KERN (https://kernsuite.info/packages/) You would need KERN4.

**Comment by texadactyl** [comment]
Try (please adjust for Windows syntax as needed):
1. ```pip install h5py blimpy bitshuffle h5py hdf5plugin```
2. Assuming that works and you see some new things being installed, re-install turbo_seti:
```
cd turbo_seti-master # wherever it is
python setup.py install
```
3. Finally, try execution:
```
turboSETI Voyager1.single_coarse.fine_res.h5
```

Hopefully, this will result in something like this:
```
blimpy.file_wrapper INFO     Skipping loading data ...
blimpy.file_wrapper INFO     Skipping loading data ...
turbo_seti.findoppler.findopp INFO     {u'telescope_id': 6, u'nbits': 32, u'fch1': 8421.386717353016, u'tstart': 57650.78209490741, u'data_type': 1, u'nchans': 1048576, u'ibeam': 1, u'tsamp': 18.253611008, u'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', u'foff': -2.7939677238464355e-06, u'DIMENSION_LABELS': array(['frequency', 'feed_id', 'time'], dtype=object), u'src_raj': <Angle 17.16777333 hourangle>, u'src_dej': <Angle 12.183 deg>, u'nbeams': 1, u'az_start': 0.0, u'source_name': 'Voyager1', u'nifs': 1, u'machine_id': 20, u'za_start': 0.0}
turbo_seti.findoppler.findopp INFO     A new FinDoppler instance created!
turbo_seti.findoppler.findopp INFO     Start ET search for Voyager1.single_coarse.fine_res.h5
turbo_seti.findoppler.findopp INFO     Start searching for coarse channel: 1
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Top hit found! SNR: 30.612128 ... index: 739933
turbo_seti.findoppler.findopp INFO     Top hit found! SNR: 245.707984 ... index: 747929
turbo_seti.findoppler.findopp INFO     Top hit found! SNR: 31.220652 ... index: 756037
turbo_seti.findoppler.findopp INFO     Total number of candidates for coarse channel 1 is: 858
Search time:  1.05 min
```

**Comment by texadactyl** [comment]
@jeenriquez - if the above Linux recipe works for @dmkunsman after she/he faithfully translates into Windowsese, then please help yourself to hack and insert into README.md.  Probably, someone with a Windows machine should translate my Linuxese into the right syntax for Windows.

**Comment by dmkunsman** [comment]
I was able to get this compiled on windows!

**Comment by texadactyl** [comment]
Celebrate by closing the issue!
