### ISSUE TITLE
Class FinDoppler(obs_info=None {default}) causes a subsequent crash

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#26]
I installed and created this Python 3 program:
```
"""
Turbo Seti FinDoppler Test
"""
from turbo_seti.findoppler.findopp import FinDoppler

DATA = "/home/elkins/data/Voyager1.single_coarse.fine_res.h5"
fd = FinDoppler(DATA, 2, out_dir="/home/elkins/Downloads")  # <------ needs obs_info=?
fd.search()
```
The input file is from github: Voyager1.single_coarse.fine_res.h5.
Program stdout:
```
blimpy.io.file_wrapper INFO     Skipping loading data ...
blimpy.io.file_wrapper INFO     Skipping loading data ...
turbo_seti.findoppler.findopp INFO     {b'DIMENSION_LABELS': array([b'frequency', b'feed_id', b'time'], dtype=object), b'az_start': 0.0, b'data_type': 1, b'fch1': 8421.386717353016, b'foff': -2.7939677238464355e-06, b'ibeam': 1, b'machine_id': 20, b'nbeams': 1, b'nbits': 32, b'nchans': 1048576, b'nifs': 1, b'rawdatafile': b'guppi_57650_67573_Voyager1_0002.0000.raw', b'source_name': b'Voyager1', b'src_dej': <Angle 12.183 deg>, b'src_raj': <Angle 17.16777333 hourangle>, b'telescope_id': 6, b'tsamp': 18.253611008, b'tstart': 57650.78209490741, b'za_start': 0.0}
turbo_seti.findoppler.findopp INFO     A new FinDoppler instance created!
turbo_seti.findoppler.findopp INFO     Start ET search for /home/elkins/data/Voyager1.single_coarse.fine_res.h5
turbo_seti.findoppler.findopp INFO     Start searching for coarse channel: 1
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
turbo_seti.findoppler.findopp INFO     Doppler correcting reverse...
etc.
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Doppler correcting forward...
turbo_seti.findoppler.findopp INFO     Top hit found! SNR: 31.220652 ... index: 292538
Traceback (most recent call last):

  File "/mnt/elkdata/linux-home-folder/projects/seti1.py", line 8, in <module>
    fd.search()

  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.1.0-py3.8-linux-x86_64.egg/turbo_seti/findoppler/findopp.py", line 80, in search
    self.search_data(target_data_obj)

  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.1.0-py3.8-linux-x86_64.egg/turbo_seti/findoppler/findopp.py", line 281, in search_data
    self.filewriter = tophitsearch(tree_findoppler_original, max_val, tsteps, nframes, data_obj.header, tdwidth, fftlen, self.max_drift,data_obj.obs_length, out_dir = self.out_dir, logwriter=self.logwriter, filewriter=self.filewriter, obs_info = self.obs_info)

  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.1.0-py3.8-linux-x86_64.egg/turbo_seti/findoppler/findopp.py", line 415, in tophitsearch
    filewriter = filewriter.report_tophit(max_val, i, (lbound, ubound), tdwidth, fftlen, header,max_val.total_n_hits,obs_info=obs_info)

  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.1.0-py3.8-linux-x86_64.egg/turbo_seti/findoppler/file_writers.py", line 123, in report_tophit
    if obs_info['SEFDs_freq'][0] > 0.:

TypeError: 'NoneType' object is not subscriptable
```
Clearly, the code is not handling the default case (obs_info=None).
I think that the code did not expect the object to ever be initialized with obs_info=None.
Unfortunately, the example on README.md is incomplete.

The README.md needs work:
(1) Installation instructions [simple]
(2) How-to specify turboSETI options and what do they meany?
(3) A complete sample Python 3 program which imports like I attempted to do ("Use as a package")
(4) Documentation for Class FinDoppler: (a) properties (E.g. obs_info) and (b) methods (get_info, search, search_data, and anything else?

**Comment by telegraphic** [comment]
Looks like the `obs_info` approach was a bit of a hack to get LOFAR data working -- close enough to a bug so labelled as such. I'll refactor this, there should clearly be a default `obs_info` in the class
