### ISSUE TITLE
find_event.py  -->  "cannot import name 'Filterbank' from 'blimpy'"

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#36]
Line 18 in find_event.py: ```from blimpy import Filterbank```

Looking at blimpy, I see no "Filterbank" class.  Not sure when line 18 was created.

Fix: Delete the statement unless I am overlooking something?

**Comment by texadactyl** [comment]
Same thing with turboSETI (not surprising):
```
turboSETI   Voyager1.single_coarse.fine_res.h5   -o .
Traceback (most recent call last):
  File "/usr/local/bin/turboSETI", line 11, in <module>
    load_entry_point('turbo-seti==1.1.1', 'console_scripts', 'turboSETI')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.1.1-py3.8-linux-x86_64.egg/turbo_seti/__init__.py", line 2, in <module>
    from .findevent import find_event,plot_event,find_scan_sets
  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.1.1-py3.8-linux-x86_64.egg/turbo_seti/findevent/find_event.py", line 18, in <module>
    from blimpy import Filterbank
ImportError: cannot import name 'Filterbank' from 'blimpy' (/home/elkins/.local/lib/python3.8/site-packages/blimpy/__init__.py)
```

**Comment by telegraphic** [comment]
The `Filterbank` has been deprecated as of blimpy 2.0.0 -- this is fixed in the recently merged `dev` branch of turbo_seti -- but this reminds me I should update the setup.py to enforce blimpy>2.0.0.

**Comment by telegraphic** [comment]
Added blimpy version requirement in https://github.com/UCBerkeleySETI/turbo_seti/blob/master/requirements.txt + closing this issue (older versions have the bytestring `b'hello != 'hello' issue too). Closing issue!
