### ISSUE TITLE
Using turbo_seti with dask needs some user guidance

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#57]
Correct source code:
```
import time
from turbo_seti.find_doppler.find_doppler import FindDoppler
NPARTITIONS = 2
DATADIR = "/mnt/elkdata/seti/data/gj380/"
DATAFILE = DATADIR + "GBT_57636_58929_GJ380_mid.h5"

print("test_basic: At entrance, __name__ = {}".format(__name__))

if __name__ == '__main__':
    find_seti_event = FindDoppler(datafile=DATAFILE, max_drift=2, out_dir=DATADIR)
    t1 = time.time()
    if NPARTITIONS == 1:
        find_seti_event.search()
    else:
        find_seti_event.search_dask(n_partitions=NPARTITIONS)
    t2 = time.time()
    print("End, find_seti_event elapsed time for NPARTITIONS={} is {} seconds"
          .format(NPARTITIONS, t2 - t1))
```
When PARTITIONS = 1 or more, it runs fine:
```
End, find_seti_event elapsed time for NPARTITIONS=1 is 159.75894284248352 seconds
```
However, when PARTITIONS > 1 and someone does not code the ```if __name__ == '__main__'``` structure, then something confusing will happen. 

Stdout with PARTITIONS = 2 and the ```if __name__ == '__main__'``` is left out:
```
[                                        ] | 0% Completed |  4.4sTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/elkins/turbo_seti_testing/test_basic.py", line 11, in <module>
    find_seti_event.search_dask(n_partitions=NPARTITIONS)
  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.2.2-py3.8-linux-x86_64.egg/turbo_seti/find_doppler/find_doppler.py", line 150, in search_dask
    m = b.map(search_data,
  File "/usr/local/lib/python3.8/dist-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dask/multiprocessing.py", line 186, in get
    pool = context.Pool(num_workers, initializer=initialize_worker_process)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Not easy to diagnose!

**Comment by texadactyl** [comment]
The ```turboSETI``` shell script invocation seems to run well and performs much better with 2 partitions (Search time:  1.50 min) compared to one (Search time:  2.82 min).  I used the same file for these 2 tests (```GBT_57636_58929_GJ380_mid.h5```).

**Comment by texadactyl** [comment]
With the above source code as-stated, all is well:
```
test_basic: At entrance, __name__ = __main__
[                                        ] | 0% Completed |  3.1s test_basic: At entrance, __name__ = __mp_main__
[                                        ] | 0% Completed |  3.5s test_basic: At entrance, __name__ = __mp_main__
[########################################] | 100% Completed |  1min 27.2s
End, find_seti_event elapsed time for NPARTITIONS=2 is 87.49659419059753 seconds
```

**Comment by texadactyl** [comment]
Could we highlight this in the next documentation update?  Inexperienced programmers could stumble over this without understanding what is going wrong.  Also, it would be helpful to have a sample program that uses the API as it should be used.
